### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by shadowlmd** [grishka/Smithereen#32]
I'd like to request a feature: healthcheck endpoint(s). This is useful to keep service healthy and avoid noticeable downtimes. Kubernetes best practices suggest to use `/healthz`, `/livez` and `/readyz` for this purpose (https://kubernetes.io/docs/reference/using-api/health-checks/). While having all 3 of them would be perfect, having at least `/healthz` seems essential currently.

**Comment by grishka** [comment]
Would it be enough to simply return a `200 OK` with an empty body?
