### ISSUE TITLE
Reposts

### ISSUE THREAD

**Issue by HSDChannel** [grishka/Smithereen#41]
How about reposts? 🤔

**Comment by grishka** [comment]
These are planned for some distant future, but they're going to be VK-style reposts where each reposts creates a separate comment thread.

**Comment by grishka** [comment]
Note to self: Pleroma already implements this style of repost https://friends.grishka.me/posts/121962

**Comment by ayaaop** [comment]
implemented? https://mastodon.social/@grishka/112299729533792125

**Comment by grishka** [comment]
Yes
