### ISSUE TITLE
Hiding sensitive content

### ISSUE THREAD

**Issue by Horhik** [grishka/Smithereen#42]
Smithereen don't hide posts marked as **sensitive content**, it hides only posts with **content warning**. 
Maybe, you can show sensitive content posts as a post with empty content warning or just with a particular header. 
![image](https://user-images.githubusercontent.com/46262811/158310055-9309cb23-f550-4df0-bac6-bdfda4affc4a.png)

The funny thing, is what there was post from mastodon, but for posts from pleroma, 
![image](https://user-images.githubusercontent.com/46262811/158310284-08b5ca49-71a9-4bbe-b49d-5415ba96b489.png)
![image](https://user-images.githubusercontent.com/46262811/158310314-01868457-1a3f-481e-b066-6d65e7651fde.png)

Situation a bit reversed...
Pictures marked as sensitive are hiding behind CW, but images with CW seems to be removing CW text

**Comment by grishka** [comment]
Fixed in f6dbb32f079e64a58dde389ca77e97cb1f4f3791
