### ISSUE TITLE
Can't attach an image when editing a wall post

### ISSUE THREAD

**Issue by akhmedovgg** [grishka/Smithereen#49]
Hi 👋
I can't attach an image when editing a wall post.

Steps to reproduce a bug:
1. Open your wall
2. Write a post
3. Try upload an image while editing your post and save

The text of the post is being edited, but the uploaded files do not appear in the post

**Comment by grishka** [comment]
Which layout are you using, desktop or mobile?

**Comment by akhmedovgg** [comment]
> Which layout are you using, desktop or mobile?

Desktop. Safari 15.6 (Latest version)
