### ISSUE TITLE
[GoToSocial] Can't follow account

### ISSUE THREAD

**Issue by SadmL** [grishka/Smithereen#77]
Account looks like locked, but in fact it's not

GoToSocial
![изображение](https://github.com/user-attachments/assets/a254e77d-7823-4caa-b166-1674cf3488a7)

Mastodon
![изображение](https://github.com/user-attachments/assets/4037252e-509e-4966-b90a-dafee065b5ed)

**Comment by grishka** [comment]
This change should now be live on friends.grishka.me

**Comment by SadmL** [comment]
Looks like it's not
> You should still be able to follow Smithereen accounts, it'll just look like you sent a follow request that was instantly accepted (which is how following works in ActivityPub anyway).


Mastodon home timeline:
![24-08-2024_03-34](https://github.com/user-attachments/assets/b25c66d4-111e-473f-a367-c0236baea3b1)

GoToSocial home timeline:
![изображение](https://github.com/user-attachments/assets/62626692-8c05-428a-ba2f-82433ecd6cd2)

But follow request was sent
![изображение](https://github.com/user-attachments/assets/983f4adb-c7f7-42ac-aa68-9deb3ccdfc1f)

**Comment by SadmL** [comment]
Also tried phone app - account still shown as locked
![Screenshot_20240824-154409_Moshidon](https://github.com/user-attachments/assets/9424d758-e676-47c6-ad05-2f7d774b2137)

**Comment by grishka** [comment]
I don't know how it works for GoToSocial, but you need to make it reload the actor object somehow. On Mastodon this can be done by pasting the origin URL (https://friends.grishka.me/danilax86) into the search.

**Comment by SadmL** [comment]
Post import counts as actor object reload?
I asking this, because I can import post via URL, but there is no refresh for account itself.

**Comment by grishka** [comment]
No, importing a post doesn't usually reload the actor

**Comment by SadmL** [comment]
I'll manage it somehow, I guess...

**Comment by SadmL** [comment]
Good news: account looks like no more locked
Bad news: still shows following request

![изображение](https://github.com/user-attachments/assets/2eae12a9-d372-4155-a871-b19968c42e9e)

And only Mastodon server in list
![изображение](https://github.com/user-attachments/assets/015cad32-f2ec-47ce-bb7d-d5c8f2b7748d)
Or friends = mutual following?
In follower account there is no my GtS account

**Comment by grishka** [comment]
Friends does mean mutual following. So your server must ignore my `Accept{Follow}` for some reason 🤔

**Comment by SadmL** [comment]
May be chat with GtS devs in this issue?
https://github.com/superseriousbusiness/gotosocial/issues/3229

**Comment by grishka** [comment]
Can you try unfollowing him and following again now?

**Comment by SadmL** [comment]
If need to reload actor object again, I must wait for 6 hours: 
https://github.com/superseriousbusiness/gotosocial/issues/3229#issuecomment-2308404994 
> if you wait 6hrs since you last fetched the account, on next fetch gotosocial will refresh the account. we put it on a cool down to limit unnecessary traffic most of the time. though most of the time accounts on servers will be kept up-to-date by sending each other Update Actor activities.

**Comment by SadmL** [comment]
Nothing changed 🤷

**Comment by SadmL** [comment]
I don't know, may be it is mutual thing, can you try follow me?
`@sl@gts.sadium.cyou`

**Comment by grishka** [comment]
Well, I can't even load the actor because of the invalid `@context`, so I suppose we found the culprit. The only thing I can fix on my side is the UI getting stuck in loading state instead of showing an error.

**Comment by SadmL** [comment]
Well-p, looks like need to wait when https://github.com/superseriousbusiness/gotosocial/issues/1947
get resolved...

**Comment by grishka** [comment]
@tsmethurst [it works!](https://friends.grishka.me/tobi@goblin.technology)
(I need to fix my CSS to stretch small avatars)

**Comment by SadmL** [comment]
After updating my instance to latest atm https://github.com/superseriousbusiness/gotosocial/commit/e10aa76612bf20ca2a5aa8e7ee5e4d1aae0ba69f, can confirm it's working
![изображение](https://github.com/user-attachments/assets/39b99ee5-5076-4cee-8b57-a82235123456)

![изображение](https://github.com/user-attachments/assets/f1a37e59-d732-4b39-823d-418c86eb6801)

**Comment by tsmethurst** [comment]
Hurray!
