### ISSUE TITLE
Support channel

### ISSUE THREAD

**Issue by handlerug** [grishka/Smithereen#8]
I thought it would be nice to have an administrators community to ask some dumb questions (can I communicate with other federations? does access_level=3 actually grant something? can I make friends with other instances?) there instead of polluting GitHub repository with more "how do I?" issues. For example, Telegram chat, IRC channel, Gitter chatroom...

**Comment by grishka** [comment]
> can I communicate with other federations?

Yes, it's mostly compatible with Mastodon, Pleroma, etc

> does access_level=3 actually grant something?

It will soon.

> can I make friends with other instances?

Yes, you can send friend requests to other Smithereen instances, and also any bilateral following counts as a friendship.

> For example, Telegram chat

Ok, I made one https://t.me/SmithereenProject

**Comment by handlerug** [comment]
> Yes, you can send friend requests to other Smithereen instances, and also any bilateral following counts as a friendship.

Hm, I couldn't find that feature. Perhaps it's not shown in the user interface?

Also two more questions:

- Should I report minor visual bugs right here in GitHub Issues? (just found one with links)

<img width="158" alt="Screenshot 2020-05-26 at 09 16 54" src="https://user-images.githubusercontent.com/24986597/82854128-b3625000-9f31-11ea-94e5-71de7397741f.png">

<img width="213" alt="Screenshot 2020-05-26 at 09 16 50" src="https://user-images.githubusercontent.com/24986597/82854121-b0fff600-9f31-11ea-949a-82d5ffcdad33.png">

- and are you open to contributions to this project or you prefer to do it alone? Just asking because I might be very annoying in the latter case.

**Comment by grishka** [comment]
> Hm, I couldn't find that feature. Perhaps it's not shown in the user interface?

Yeah it's kinda hidden right now. There's no support for "external interaction", as in you can't follow someone by entering your username@domain like you can on Mastodon — I haven't made that part yet. But, you can do it one of two ways:
* Go to `/activitypub/externalInteraction?uri=https://remote.server/actor` and send a friend request from there
* Open the remote profile locally, assuming it's already in the database: `https://your.instance/actor@remote.server`

> Should I report minor visual bugs right here in GitHub Issues? (just found one with links)

Yes please, but I fixed this particular one yesterday ;)

> and are you open to contributions to this project or you prefer to do it alone?

It depends. I'm totally okay with minor bug fixes. But for new features, I'd prefer to do them myself, for now.

**Comment by handlerug** [comment]
Ok, thanks for response and your understanding!
