### ISSUE TITLE
Graffiti not being saved as it was drawn

### ISSUE THREAD

**Issue by broadwaylamb** [grishka/Smithereen#83]
See the attached video. Note how the eyes of the smiley are missing in the finalized attachment.

https://github.com/user-attachments/assets/e30019b6-d061-4b26-8772-e9eaf8cb3f37

**Comment by grishka** [comment]
Must be an issue with how zero-length lines are rendered in svg vs canvas, though I thought I fixed it 🤔

Which browser is that?

**Comment by broadwaylamb** [comment]
Thanks, it works now.
