### ISSUE TITLE
Photos uploaded via Firefox are too small

### ISSUE THREAD

**Issue by broadwaylamb** [grishka/Smithereen#87]
The photo is exactly the same, just uploaded with different browsers.

- [Exhibit A](https://ultracycl.ing/photos/O9KlrNS04Tw) (uploaded via Firefox 131.0.2)
  <img width="1494" alt="Screenshot 2024-10-24 at 23 38 40" src="https://github.com/user-attachments/assets/8560dd35-8463-4746-bfba-0b31ccc68a67">

- [Exhibit B](https://ultracycl.ing/photos/bdBpHN-whfY) (uploaded via Safari Desktop 18.0)
   <img width="1485" alt="Screenshot 2024-10-24 at 23 38 49" src="https://github.com/user-attachments/assets/da427974-e3c8-45f4-bf56-a59cc613c59a">

**Comment by broadwaylamb** [comment]
Okay, it seems like it only happens specifically when drag & dropping images from the standard macOS Photos.app. 

Photos.app for some reason exports dragged images in the 1024x768 resolution.

But not if you're dragging into Safari. Photos exported to Safari retain their original size.

**Comment by grishka** [comment]
Oof. So it's Apple being Apple again. I looked at it out of curiosity using the "Clipboard Viewer.app" that comes as part of "additional tools for Xcode". When you drag a file from Finder, this is what you get, just various references to the file:
![Снимок экрана 2024-10-25 в 23 20 07](https://github.com/user-attachments/assets/06c0a6d4-2ce6-4b40-8ba5-72489c2cb0f9)

But when you drag a photo out of Photos.app, you get a lot more data types *in addition* to file references, including jpeg data:
![Снимок экрана 2024-10-25 в 23 20 54](https://github.com/user-attachments/assets/bc10970e-70ae-4f60-82cf-5af4a9e03808)

**Comment by broadwaylamb** [comment]
I've just tried to do this with VK and VK doesn't have this problem, this gives me hope that maybe it's possible to fix

**Comment by broadwaylamb** [comment]
Or not. No, actually VK _does_ have this problem.

**Comment by broadwaylamb** [comment]
Reported to Mozilla https://bugzilla.mozilla.org/show_bug.cgi?id=1927213

**Comment by grishka** [comment]
Thank you!
