### ISSUE TITLE
Applications throws when accessing /activitypub

### ISSUE THREAD

**Issue by handlerug** [grishka/Smithereen#9]
![image](https://user-images.githubusercontent.com/24986597/89159831-45be4a00-d59a-11ea-833a-c17f9e26b9ab.png)

**Comment by grishka** [comment]
Fixed but the layout there isn't ideal lol

**Comment by handlerug** [comment]
I wonder how did you fix that without doing any code or you just didn't push changes to GitHub yet

**Comment by grishka** [comment]
I'm rewriting a lot of things to introduce mobile-friendly layouts that use a separate set of templates wherever appropriate. And I don't like the idea of committing code that doesn't yet fully work.
